version: '2'

services:

  orderer.toycorp.com:
    container_name: orderer.toycorp.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
        - ../crypto-config/ordererOrganizations/toycorp.com/orderers/orderer.toycorp.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/toycorp.com/orderers/orderer.toycorp.com/tls/:/var/hyperledger/orderer/tls
        - orderer.toycorp.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.sales.toycorp.com:
    container_name: peer0.sales.toycorp.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.sales.toycorp.com
      - CORE_PEER_ADDRESS=peer0.sales.toycorp.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.sales.toycorp.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.sales.toycorp.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.sales.toycorp.com:7051
      - CORE_PEER_LOCALMSPID=SalesMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/sales.toycorp.com/peers/peer0.sales.toycorp.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/sales.toycorp.com/peers/peer0.sales.toycorp.com/tls:/etc/hyperledger/fabric/tls
        - peer0.sales.toycorp.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer0.accounting.toycorp.com:
    container_name: peer0.accounting.toycorp.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.accounting.toycorp.com
      - CORE_PEER_ADDRESS=peer0.accounting.toycorp.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.accounting.toycorp.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.accounting.toycorp.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.accounting.toycorp.com:10051
      - CORE_PEER_LOCALMSPID=AccountingMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/accounting.toycorp.com/peers/peer0.accounting.toycorp.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/accounting.toycorp.com/peers/peer0.accounting.toycorp.com/tls:/etc/hyperledger/fabric/tls
        - peer0.accounting.toycorp.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer0.legal.toycorp.com:
    container_name: peer0.legal.toycorp.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.legal.toycorp.com
      - CORE_PEER_ADDRESS=peer0.legal.toycorp.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.legal.toycorp.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.legal.toycorp.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.legal.toycorp.com:12051
      - CORE_PEER_LOCALMSPID=LegalMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/legal.toycorp.com/peers/peer0.legal.toycorp.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/legal.toycorp.com/peers/peer0.legal.toycorp.com/tls:/etc/hyperledger/fabric/tls
        - peer0.legal.toycorp.com:/var/hyperledger/production
    ports:
      - 11051:11051
