version: '2'

volumes:
  orderer.toycorp.com:
  peer0.sales.toycorp.com:
  peer0.accounting.toycorp.com:
  peer0.legal.toycorp.com:
  cli.sales.toycorp.com:
  cli.accounting.toycorp.com:
  cli.legal.toycorp.com:

networks:
  toycorp:

services:

  orderer.toycorp.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.toycorp.com
    container_name: orderer.toycorp.com
    networks:
      - toycorp

  peer0.sales.toycorp.com:
    container_name: peer0.sales.toycorp.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.sales.toycorp.com
    networks:
      - toycorp

  peer0.accounting.toycorp.com:
    container_name: peer0.accounting.toycorp.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.accounting.toycorp.com
    networks:
      - toycorp

  peer0.legal.toycorp.com:
    container_name: peer0.legal.toycorp.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.legal.toycorp.com
    networks:
      - toycorp

  cli-sales:
    container_name: cli.sales.toycorp.com
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.sales.toycorp.com:7051
      - CORE_PEER_LOCALMSPID=SalesMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sales.toycorp.com/peers/peer0.sales.toycorp.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sales.toycorp.com/peers/peer0.sales.toycorp.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sales.toycorp.com/peers/peer0.sales.toycorp.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sales.toycorp.com/users/Admin@sales.toycorp.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.toycorp.com
      - peer0.sales.toycorp.com
    networks:
      - toycorp

  cli-accounting:
    container_name: cli.accounting.toycorp.com
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.accounting.toycorp.com:9051
      - CORE_PEER_LOCALMSPID=AccountingMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/accounting.toycorp.com/peers/peer0.accounting.toycorp.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/accounting.toycorp.com/peers/peer0.accounting.toycorp.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/accounting.toycorp.com/peers/peer0.accounting.toycorp.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/accounting.toycorp.com/users/Admin@accounting.toycorp.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.toycorp.com
      - peer0.accounting.toycorp.com
    networks:
      - toycorp


  cli-legal:
    container_name: cli.legal.toycorp.com
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.legal.toycorp.com:11051
      - CORE_PEER_LOCALMSPID=LegalMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/legal.toycorp.com/peers/peer0.legal.toycorp.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/legal.toycorp.com/peers/peer0.legal.toycorp.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/legal.toycorp.com/peers/peer0.legal.toycorp.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/legal.toycorp.com/users/Admin@legal.toycorp.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.toycorp.com
      - peer0.legal.toycorp.com
    networks:
      - toycorp
